### Department of Biostatistics:

#### &#8195;The Department of Biostatistics was established in 2015, separated from the department of Epidemiology and Biostatistics. The department undertakes the teaching task of Medical Statistics (modules A, B and C), Advanced Medical Statistics and Multi-Variate Statistics among all four-year, five-year undergraduates, seven-year students, postgraduates and adults in continuing education program. The department also offers specialized courses and professional training to students who majored in Biostatistics. Additionally, the department focuses on researches of statistical analysis strategies, methods and application. All faculty, staff and students can turn to the department for consulting statistical problems.

#### &#8195;The department has 2 professors, 5 associate professors and 8 lectures and 1 teaching assistant. Most of them have Ph.D degrees and researching, studying or visiting experiences in well-known colleges or research institutions.

#### &#8195;The research interests of the faculty members include:

+ &#8195;Statistical methodology and application in the analysis of biomedical big data
+ &#8195;Statistical methodology for clinical trials
+ &#8195;Infectious disease dynamics model

<br>
<br>
<br>

#### **Add:**  101Longmian Avenue, Jiangning District, Nanjing 211166, P.R. China
#### **Tel:**  
#### **Fax:**  
#### **E-mail:**  YongYue Wei, <<ywei@njmu.edu.cn>>;
#### &#8195;&#8195;&#8195; Feng Chen, <<fengchen@njmu.edu.cn>>

